"""Runtime public exports, loaded only when their backend is requested."""

from importlib import import_module as _import_module

_EXPORTS = {
    "RuntimeBootstrapResult": "pcketlm.core.runtime.bootstrap",
    "RuntimeDependencyStatus": "pcketlm.core.runtime.bootstrap",
    "build_runtime_bootstrap": "pcketlm.core.runtime.bootstrap",
    "create_runtime_session": "pcketlm.core.runtime.bootstrap",
    "RuntimeLoadAttemptResult": "pcketlm.core.runtime.load_attempt",
    "attempt_real_model_load": "pcketlm.core.runtime.load_attempt",
    "RuntimeBackendCandidate": "pcketlm.core.runtime.engine_selector",
    "RuntimeBackendReport": "pcketlm.core.runtime.engine_selector",
    "RuntimeEngineDecision": "pcketlm.core.runtime.engine_selector",
    "build_runtime_backend_report": "pcketlm.core.runtime.engine_selector",
    "select_runtime_engine": "pcketlm.core.runtime.engine_selector",
    "GGUFBackendStatus": "pcketlm.core.runtime.gguf_backend",
    "GGUFModelFile": "pcketlm.core.runtime.gguf_backend",
    "GGUFPromptResult": "pcketlm.core.runtime.gguf_backend",
    "GGUFServerStatus": "pcketlm.core.runtime.gguf_backend",
    "build_gguf_backend_status": "pcketlm.core.runtime.gguf_backend",
    "build_gguf_server_status": "pcketlm.core.runtime.gguf_backend",
    "estimate_gguf_load_cost": "pcketlm.core.runtime.gguf_backend",
    "find_gguf_model_files": "pcketlm.core.runtime.gguf_backend",
    "run_gguf_prompt": "pcketlm.core.runtime.gguf_backend",
    "start_gguf_server": "pcketlm.core.runtime.gguf_backend",
    "stop_gguf_server": "pcketlm.core.runtime.gguf_backend",
    "summarize_gguf_artifacts": "pcketlm.core.runtime.gguf_backend",
    "StreamingMaterializationResult": "pcketlm.core.runtime.streaming_materialize",
    "materialize_window_schedule": "pcketlm.core.runtime.streaming_materialize",
    "TensorCatalog": "pcketlm.core.runtime.tensor_catalog",
    "TensorCatalogEntry": "pcketlm.core.runtime.tensor_catalog",
    "build_tensor_catalog": "pcketlm.core.runtime.tensor_catalog",
    "TensorExecutionPlan": "pcketlm.core.runtime.tensor_execution_plan",
    "TensorExecutionUnit": "pcketlm.core.runtime.tensor_execution_plan",
    "build_tensor_execution_plan": "pcketlm.core.runtime.tensor_execution_plan",
    "ExecutionUnitVerificationResult": "pcketlm.core.runtime.tensor_loader",
    "LoadedExecutionUnit": "pcketlm.core.runtime.tensor_loader",
    "LoadedTensorSlice": "pcketlm.core.runtime.tensor_loader",
    "load_execution_unit": "pcketlm.core.runtime.tensor_loader",
    "load_tensor_by_name": "pcketlm.core.runtime.tensor_loader",
    "verify_execution_unit": "pcketlm.core.runtime.tensor_loader",
    "verify_loaded_tensor": "pcketlm.core.runtime.tensor_loader",
    "TensorVerificationResult": "pcketlm.core.runtime.tensor_loader",
    "FP8DequantizedTensor": "pcketlm.core.runtime.fp8_source",
    "FP8AttentionResult": "pcketlm.core.runtime.fp8_source",
    "FP8BlockResult": "pcketlm.core.runtime.fp8_source",
    "FP8DecodeTailBatchResult": "pcketlm.core.runtime.fp8_source",
    "FP8DecodeTailResult": "pcketlm.core.runtime.fp8_source",
    "FP8DecodeLoopResult": "pcketlm.core.runtime.fp8_source",
    "FP8DenseMLPResult": "pcketlm.core.runtime.fp8_source",
    "FP8ExpertMLPResult": "pcketlm.core.runtime.fp8_source",
    "FP8LayerWorkingSet": "pcketlm.core.runtime.fp8_source",
    "FP8MoEResult": "pcketlm.core.runtime.fp8_source",
    "FP8PromptPrefillBatchResult": "pcketlm.core.runtime.fp8_source",
    "FP8PromptPrefillResult": "pcketlm.core.runtime.fp8_source",
    "FP8RouterResult": "pcketlm.core.runtime.fp8_source",
    "FP8TokenEmbeddingResult": "pcketlm.core.runtime.fp8_source",
    "FP8TokenForwardResult": "pcketlm.core.runtime.fp8_source",
    "FP8TensorPair": "pcketlm.core.runtime.fp8_source",
    "clear_fp8_prefill_cache": "pcketlm.core.runtime.fp8_source",
    "clear_fp8_lm_head_full_cache": "pcketlm.core.runtime.fp8_source",
    "clear_fp8_regular_tensor_cache": "pcketlm.core.runtime.fp8_source",
    "dequantize_fp8_block_scaled": "pcketlm.core.runtime.fp8_source",
    "dequantize_fp8_weight_pair": "pcketlm.core.runtime.fp8_source",
    "fp8_lm_head_full_cache_snapshot": "pcketlm.core.runtime.fp8_source",
    "fp8_prefill_cache_snapshot": "pcketlm.core.runtime.fp8_source",
    "fp8_regular_tensor_cache_snapshot": "pcketlm.core.runtime.fp8_source",
    "fp8_residency_split_snapshot": "pcketlm.core.runtime.fp8_source",
    "fp8_source_status": "pcketlm.core.runtime.fp8_source",
    "apply_fp8_exact_mtp_default_env": "pcketlm.core.runtime.fp8_source",
    "load_dequantized_fp8_weight": "pcketlm.core.runtime.fp8_source",
    "load_fp8_token_embedding": "pcketlm.core.runtime.fp8_source",
    "load_fp8_weight_pair": "pcketlm.core.runtime.fp8_source",
    "plan_fp8_layer_working_set": "pcketlm.core.runtime.fp8_source",
    "run_fp8_expert_mlp": "pcketlm.core.runtime.fp8_source",
    "run_fp8_dense_mlp": "pcketlm.core.runtime.fp8_source",
    "run_fp8_decode_tail_topk_batch": "pcketlm.core.runtime.fp8_source",
    "run_fp8_decode_tail_topk": "pcketlm.core.runtime.fp8_source",
    "run_fp8_decode_loop": "pcketlm.core.runtime.fp8_source",
    "run_fp8_mtp_batched_generate": "pcketlm.core.runtime.fp8_source",
    "run_fp8_mtp_batched_generate_from_tokens": "pcketlm.core.runtime.fp8_source",
    "warm_fp8_mtp_prompt_prefill_cache": "pcketlm.core.runtime.fp8_source",
    "warm_fp8_mtp_prompt_prefill_cache_from_tokens": "pcketlm.core.runtime.fp8_source",
    "run_fp8_moe": "pcketlm.core.runtime.fp8_source",
    "run_fp8_prompt_prefill_batch": "pcketlm.core.runtime.fp8_source",
    "run_fp8_prompt_prefill": "pcketlm.core.runtime.fp8_source",
    "run_fp8_router": "pcketlm.core.runtime.fp8_source",
    "run_fp8_single_token_attention": "pcketlm.core.runtime.fp8_source",
    "run_fp8_single_token_block": "pcketlm.core.runtime.fp8_source",
    "run_fp8_single_token_forward": "pcketlm.core.runtime.fp8_source",
    "DeepSeekGPUResidencyEstimate": "pcketlm.core.runtime.deepseek_gpu_residency",
    "LocalDeepSeekPagedDecodeLoopResult": "pcketlm.core.runtime.deepseek_gpu_residency",
    "LocalDeepSeekPagedDecodeResult": "pcketlm.core.runtime.deepseek_gpu_residency",
    "LocalDeepSeekResidentLayer": "pcketlm.core.runtime.deepseek_gpu_residency",
    "LocalDeepSeekResidentLayerPager": "pcketlm.core.runtime.deepseek_gpu_residency",
    "estimate_deepseek_gpu_residency": "pcketlm.core.runtime.deepseek_gpu_residency",
    "run_local_deepseek_paged_decode_loop": "pcketlm.core.runtime.deepseek_gpu_residency",
    "run_local_deepseek_paged_decode_probe": "pcketlm.core.runtime.deepseek_gpu_residency",
    "DEFAULT_LM_HEAD_CHUNK_ROWS": "pcketlm.core.runtime.layer_bridge",
    "DecodeBenchmarkCaseResult": "pcketlm.core.runtime.layer_bridge",
    "DecodeBenchmarkResult": "pcketlm.core.runtime.layer_bridge",
    "DecodeTailResult": "pcketlm.core.runtime.layer_bridge",
    "KVDecodeState": "pcketlm.core.runtime.layer_bridge",
    "KVDecodeLoopResult": "pcketlm.core.runtime.layer_bridge",
    "KVDecodeStepResult": "pcketlm.core.runtime.layer_bridge",
    "LayerBridgeModelConfig": "pcketlm.core.runtime.layer_bridge",
    "LayerBridgeResult": "pcketlm.core.runtime.layer_bridge",
    "LayerBridgeStackResult": "pcketlm.core.runtime.layer_bridge",
    "LayerBridgeStepSummary": "pcketlm.core.runtime.layer_bridge",
    "PromptDecodeLoopResult": "pcketlm.core.runtime.layer_bridge",
    "RepeatedDecodeLoopResult": "pcketlm.core.runtime.layer_bridge",
    "RepeatedDecodeStepSummary": "pcketlm.core.runtime.layer_bridge",
    "TokenDecodeStepResult": "pcketlm.core.runtime.layer_bridge",
    "TokenEntryBridgeResult": "pcketlm.core.runtime.layer_bridge",
    "build_history_summary_hidden_state": "pcketlm.core.runtime.layer_bridge",
    "configure_runtime_threads": "pcketlm.core.runtime.layer_bridge",
    "initialize_kv_decode_state": "pcketlm.core.runtime.layer_bridge",
    "load_token_entry_hidden_state": "pcketlm.core.runtime.layer_bridge",
    "load_layer_bridge_config": "pcketlm.core.runtime.layer_bridge",
    "run_decode_benchmark": "pcketlm.core.runtime.layer_bridge",
    "run_prompt_decode_loop": "pcketlm.core.runtime.layer_bridge",
    "run_prompt_prefill_session": "pcketlm.core.runtime.layer_bridge",
    "runtime_math_dtype_name": "pcketlm.core.runtime.layer_bridge",
    "runtime_torch_thread_count": "pcketlm.core.runtime.layer_bridge",
    "run_kv_decode_loop": "pcketlm.core.runtime.layer_bridge",
    "run_kv_decode_step": "pcketlm.core.runtime.layer_bridge",
    "run_decode_tail": "pcketlm.core.runtime.layer_bridge",
    "run_layer_bridge_stack": "pcketlm.core.runtime.layer_bridge",
    "run_minimal_layer_forward_bridge": "pcketlm.core.runtime.layer_bridge",
    "run_repeated_decode_loop": "pcketlm.core.runtime.layer_bridge",
    "run_token_decode_step": "pcketlm.core.runtime.layer_bridge",
    "run_token_entry_layer_bridge": "pcketlm.core.runtime.layer_bridge",
    "StreamingControlExecutionResult": "pcketlm.core.runtime.streaming_control",
    "StreamingControlState": "pcketlm.core.runtime.streaming_control",
    "advance_streaming_runtime": "pcketlm.core.runtime.streaming_control",
    "advance_streaming_runtime_safely": "pcketlm.core.runtime.streaming_control",
    "build_streaming_control_state": "pcketlm.core.runtime.streaming_control",
    "StreamingResidencyState": "pcketlm.core.runtime.streaming_residency",
    "load_streaming_residency": "pcketlm.core.runtime.streaming_residency",
    "write_streaming_residency": "pcketlm.core.runtime.streaming_residency",
    "StreamingRotationResult": "pcketlm.core.runtime.streaming_rotation",
    "rotate_window_schedule": "pcketlm.core.runtime.streaming_rotation",
    "StreamingManifestView": "pcketlm.core.runtime.streaming_reader",
    "load_streaming_manifest": "pcketlm.core.runtime.streaming_reader",
    "StreamingUnitMap": "pcketlm.core.runtime.streaming_units",
    "build_streaming_unit_map": "pcketlm.core.runtime.streaming_units",
    "write_streaming_unit_map": "pcketlm.core.runtime.streaming_units",
    "WindowSchedule": "pcketlm.core.runtime.window_schedule",
    "build_window_schedule": "pcketlm.core.runtime.window_schedule",
    "write_window_schedule": "pcketlm.core.runtime.window_schedule",
    "RuntimeStrategyOption": "pcketlm.core.runtime.strategy",
    "RuntimeStrategyPlan": "pcketlm.core.runtime.strategy",
    "plan_reduced_memory_strategy": "pcketlm.core.runtime.strategy",
    "StreamingPlan": "pcketlm.core.runtime.streaming",
    "plan_staged_disk_streaming": "pcketlm.core.runtime.streaming",
    "StreamingBootstrapResult": "pcketlm.core.runtime.streaming_state",
    "bootstrap_streaming_state": "pcketlm.core.runtime.streaming_state",
    "write_streaming_manifest": "pcketlm.core.runtime.streaming_state",
    "RuntimeSourceDescriptor": "pcketlm.core.runtime.source",
    "describe_runtime_source": "pcketlm.core.runtime.source",
    "WarmRunner": "pcketlm.core.runtime.warm_runner",
    "WarmRunnerRequestResult": "pcketlm.core.runtime.warm_runner",
    "run_warm_agent_prompt": "pcketlm.core.runtime.warm_runner",
    "start_warm_runner": "pcketlm.core.runtime.warm_runner",
    "stop_warm_runner": "pcketlm.core.runtime.warm_runner",
    "warm_runner_memory_snapshot": "pcketlm.core.runtime.warm_runner",
    "warm_runner_status": "pcketlm.core.runtime.warm_runner"
}


def __getattr__(name):
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(_import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(_EXPORTS))


__all__ = [
    "RuntimeBootstrapResult",
    "RuntimeDependencyStatus",
    "RuntimeLoadAttemptResult",
    "RuntimeBackendCandidate",
    "RuntimeBackendReport",
    "RuntimeEngineDecision",
    "GGUFBackendStatus",
    "GGUFModelFile",
    "GGUFPromptResult",
    "GGUFServerStatus",
    "RuntimeStrategyOption",
    "RuntimeStrategyPlan",
    "StreamingBootstrapResult",
    "StreamingControlExecutionResult",
    "StreamingControlState",
    "StreamingManifestView",
    "StreamingMaterializationResult",
    "StreamingResidencyState",
    "StreamingRotationResult",
    "StreamingUnitMap",
    "TensorCatalog",
    "TensorCatalogEntry",
    "TensorExecutionPlan",
    "TensorExecutionUnit",
    "LoadedExecutionUnit",
    "LoadedTensorSlice",
    "ExecutionUnitVerificationResult",
    "TensorVerificationResult",
    "FP8LayerWorkingSet",
    "FP8TensorPair",
    "FP8DequantizedTensor",
    "FP8AttentionResult",
    "FP8BlockResult",
    "FP8DecodeTailBatchResult",
    "FP8DecodeTailResult",
    "FP8DecodeLoopResult",
    "FP8DenseMLPResult",
    "FP8ExpertMLPResult",
    "FP8RouterResult",
    "FP8MoEResult",
    "FP8PromptPrefillResult",
    "FP8TokenEmbeddingResult",
    "FP8TokenForwardResult",
    "DeepSeekGPUResidencyEstimate",
    "LocalDeepSeekPagedDecodeLoopResult",
    "LocalDeepSeekPagedDecodeResult",
    "LocalDeepSeekResidentLayer",
    "LocalDeepSeekResidentLayerPager",
    "clear_fp8_prefill_cache",
    "clear_fp8_lm_head_full_cache",
    "clear_fp8_regular_tensor_cache",
    "DecodeBenchmarkCaseResult",
    "DecodeBenchmarkResult",
    "DecodeTailResult",
    "DEFAULT_LM_HEAD_CHUNK_ROWS",
    "KVDecodeState",
    "KVDecodeLoopResult",
    "KVDecodeStepResult",
    "LayerBridgeModelConfig",
    "LayerBridgeResult",
    "LayerBridgeStackResult",
    "LayerBridgeStepSummary",
    "PromptDecodeLoopResult",
    "RepeatedDecodeLoopResult",
    "RepeatedDecodeStepSummary",
    "TokenDecodeStepResult",
    "TokenEntryBridgeResult",
    "WindowSchedule",
    "RuntimeSourceDescriptor",
    "WarmRunner",
    "WarmRunnerRequestResult",
    "StreamingPlan",
    "attempt_real_model_load",
    "advance_streaming_runtime",
    "advance_streaming_runtime_safely",
    "bootstrap_streaming_state",
    "build_streaming_unit_map",
    "build_streaming_control_state",
    "build_window_schedule",
    "build_runtime_bootstrap",
    "create_runtime_session",
    "build_tensor_catalog",
    "build_tensor_execution_plan",
    "build_history_summary_hidden_state",
    "configure_runtime_threads",
    "initialize_kv_decode_state",
    "run_decode_benchmark",
    "run_prompt_decode_loop",
    "run_prompt_prefill_session",
    "run_warm_agent_prompt",
    "runtime_math_dtype_name",
    "runtime_torch_thread_count",
    "build_runtime_backend_report",
    "build_gguf_backend_status",
    "build_gguf_server_status",
    "estimate_gguf_load_cost",
    "find_gguf_model_files",
    "run_gguf_prompt",
    "start_gguf_server",
    "stop_gguf_server",
    "summarize_gguf_artifacts",
    "start_warm_runner",
    "stop_warm_runner",
    "warm_runner_memory_snapshot",
    "warm_runner_status",
    "select_runtime_engine",
    "run_decode_tail",
    "run_kv_decode_loop",
    "run_kv_decode_step",
    "load_layer_bridge_config",
    "load_token_entry_hidden_state",
    "run_layer_bridge_stack",
    "load_execution_unit",
    "load_tensor_by_name",
    "load_fp8_weight_pair",
    "load_fp8_token_embedding",
    "load_dequantized_fp8_weight",
    "fp8_source_status",
    "plan_fp8_layer_working_set",
    "dequantize_fp8_block_scaled",
    "dequantize_fp8_weight_pair",
    "fp8_lm_head_full_cache_snapshot",
    "fp8_prefill_cache_snapshot",
    "fp8_regular_tensor_cache_snapshot",
    "fp8_residency_split_snapshot",
    "apply_fp8_exact_mtp_default_env",
    "estimate_deepseek_gpu_residency",
    "run_fp8_expert_mlp",
    "run_fp8_dense_mlp",
    "run_fp8_decode_tail_topk_batch",
    "run_fp8_decode_tail_topk",
    "run_fp8_decode_loop",
    "run_fp8_mtp_batched_generate",
    "run_fp8_mtp_batched_generate_from_tokens",
    "run_local_deepseek_paged_decode_loop",
    "run_local_deepseek_paged_decode_probe",
    "warm_fp8_mtp_prompt_prefill_cache",
    "warm_fp8_mtp_prompt_prefill_cache_from_tokens",
    "run_fp8_router",
    "run_fp8_moe",
    "run_fp8_prompt_prefill_batch",
    "run_fp8_prompt_prefill",
    "run_fp8_single_token_attention",
    "run_fp8_single_token_block",
    "run_fp8_single_token_forward",
    "run_repeated_decode_loop",
    "verify_execution_unit",
    "verify_loaded_tensor",
    "run_minimal_layer_forward_bridge",
    "run_token_decode_step",
    "run_token_entry_layer_bridge",
    "describe_runtime_source",
    "load_streaming_manifest",
    "load_streaming_residency",
    "materialize_window_schedule",
    "rotate_window_schedule",
    "plan_reduced_memory_strategy",
    "plan_staged_disk_streaming",
    "write_window_schedule",
    "write_streaming_unit_map",
    "write_streaming_manifest",
    "write_streaming_residency",
]
