"""Submit and poll the PLM-14 GPU smoke on Kaggle.

This keeps the recurring GPU test loop terminal-driven instead of requiring the
operator to open Colab and click through a notebook every time.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SMOKE_MODULE = ROOT / "src" / "pcketlm" / "core" / "runtime" / "gpu_smoke.py"
DEFAULT_BUILD_DIR = ROOT / "build" / "kaggle_gpu_smoke"
DEFAULT_STATE_DIR = ROOT / "state" / "kaggle_gpu_smoke"


@dataclass(frozen=True)
class KaggleCredentials:
    username: str | None
    available: bool
    source: str
    message: str


def kaggle_credentials() -> KaggleCredentials:
    env_user = os.environ.get("KAGGLE_USERNAME")
    env_key = os.environ.get("KAGGLE_KEY")
    if env_user and env_key:
        return KaggleCredentials(env_user, True, "environment", "KAGGLE_USERNAME/KAGGLE_KEY are set.")

    config = Path.home() / ".kaggle" / "kaggle.json"
    if config.exists():
        try:
            data = json.loads(config.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            return KaggleCredentials(None, False, str(config), f"Invalid kaggle.json: {exc}")
        username = data.get("username")
        key = data.get("key")
        if username and key:
            return KaggleCredentials(str(username), True, str(config), "kaggle.json is present.")
        return KaggleCredentials(None, False, str(config), "kaggle.json is missing username or key.")

    return KaggleCredentials(
        None,
        False,
        str(config),
        "Kaggle credentials are missing. Create an API token on Kaggle and save it as ~/.kaggle/kaggle.json.",
    )


def _run(command: list[str], *, cwd: Path | None = None, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=cwd, check=check, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)


def _git_value(args: list[str], fallback: str) -> str:
    try:
        return _run(["git", *args], cwd=ROOT).stdout.strip() or fallback
    except (subprocess.CalledProcessError, FileNotFoundError):
        return fallback


def _repo_url() -> str:
    return _git_value(["config", "--get", "remote.origin.url"], "https://github.com/iamlicht1f1-maker/pcketlm.git")


def _branch_name() -> str:
    return _git_value(["branch", "--show-current"], "plm-14-gpu-testing-pipeline")


def _commit_sha() -> str:
    return _git_value(["rev-parse", "--short", "HEAD"], "unknown")


def _kernel_script(*, repo_url: str, branch: str, commit: str) -> str:
    smoke_source = SMOKE_MODULE.read_text(encoding="utf-8")
    return "\n".join(
        [
            "# Auto-generated by tools/kaggle_gpu_smoke.py.",
            f"SOURCE_REPO_URL = {repo_url!r}",
            f"SOURCE_BRANCH = {branch!r}",
            f"SOURCE_COMMIT = {commit!r}",
            smoke_source,
            "",
            "if __name__ == \"__main__\":",
            "    print(\"PCKETLM_KAGGLE_GPU_SMOKE_START\")",
            "    print(f\"source_repo={SOURCE_REPO_URL}\")",
            "    print(f\"source_branch={SOURCE_BRANCH}\")",
            "    print(f\"source_commit={SOURCE_COMMIT}\")",
            "    result = run_gpu_smoke(require_cuda=True)",
            "    print(\"PCKETLM_GPU_SMOKE_JSON_START\")",
            "    print(json.dumps(result.to_dict(), indent=2, sort_keys=True))",
            "    print(\"PCKETLM_GPU_SMOKE_JSON_END\")",
            "    raise SystemExit(0 if result.passed and result.cuda_available else 1)",
            "",
        ]
    )


def prepare_kernel(
    *,
    username: str,
    slug: str,
    title: str,
    out_dir: Path = DEFAULT_BUILD_DIR,
    repo_url: str | None = None,
    branch: str | None = None,
    commit: str | None = None,
) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    script_name = "gpu_smoke_kaggle.py"
    repo_url = repo_url or _repo_url()
    branch = branch or _branch_name()
    commit = commit or _commit_sha()

    metadata: dict[str, Any] = {
        "id": f"{username}/{slug}",
        "title": title,
        "code_file": script_name,
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_internet": False,
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }
    (out_dir / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (out_dir / script_name).write_text(
        _kernel_script(repo_url=repo_url, branch=branch, commit=commit),
        encoding="utf-8",
    )
    return out_dir


def ensure_kaggle_package() -> None:
    if shutil.which("kaggle"):
        return
    _run([sys.executable, "-m", "pip", "install", "--user", "kaggle"])


def _kaggle_command(args: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    ensure_kaggle_package()
    executable = shutil.which("kaggle")
    if executable:
        return _run([executable, *args], check=check)
    return _run([sys.executable, "-m", "kaggle", *args], check=check)


def submit_kernel(kernel_dir: Path) -> str:
    return _kaggle_command(["kernels", "push", "-p", str(kernel_dir)]).stdout


def poll_kernel(kernel_id: str, *, interval_seconds: int, timeout_seconds: int) -> str:
    deadline = time.time() + timeout_seconds
    last_output = ""
    while time.time() < deadline:
        completed = _kaggle_command(["kernels", "status", kernel_id], check=False)
        last_output = completed.stdout
        lowered = last_output.lower()
        if "complete" in lowered or "error" in lowered or "failed" in lowered or "cancel" in lowered:
            return last_output
        time.sleep(interval_seconds)
    return last_output + f"\nTimed out after {timeout_seconds} seconds."


def download_output(kernel_id: str, out_dir: Path) -> str:
    out_dir.mkdir(parents=True, exist_ok=True)
    return _kaggle_command(["kernels", "output", kernel_id, "-p", str(out_dir)], check=False).stdout


def write_state(payload: dict[str, Any], *, state_dir: Path = DEFAULT_STATE_DIR) -> Path:
    state_dir.mkdir(parents=True, exist_ok=True)
    path = state_dir / "latest.json"
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run the PLM-14 GPU smoke on Kaggle.")
    parser.add_argument("--slug", default="pcketlm-gpu-smoke", help="Kaggle kernel slug.")
    parser.add_argument("--title", default="PocketLM GPU Smoke", help="Kaggle kernel title.")
    parser.add_argument("--prepare-only", action="store_true", help="Only write the Kaggle kernel folder.")
    parser.add_argument("--poll-interval", type=int, default=30, help="Poll interval in seconds.")
    parser.add_argument("--timeout", type=int, default=900, help="Poll timeout in seconds.")
    args = parser.parse_args(argv)

    creds = kaggle_credentials()
    username = creds.username or "missing-kaggle-user"
    kernel_dir = prepare_kernel(username=username, slug=args.slug, title=args.title)
    kernel_id = f"{username}/{args.slug}"
    payload: dict[str, Any] = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "kernel_id": kernel_id,
        "kernel_dir": str(kernel_dir),
        "credentials_available": creds.available,
        "credentials_source": creds.source,
        "credentials_message": creds.message,
        "source_repo": _repo_url(),
        "source_branch": _branch_name(),
        "source_commit": _commit_sha(),
    }

    if args.prepare_only:
        payload["status"] = "prepared"
        print(json.dumps(payload, indent=2, sort_keys=True))
        write_state(payload)
        return 0

    if not creds.available:
        payload["status"] = "blocked_missing_kaggle_credentials"
        print(json.dumps(payload, indent=2, sort_keys=True))
        write_state(payload)
        return 2

    submit_output = submit_kernel(kernel_dir)
    status_output = poll_kernel(kernel_id, interval_seconds=args.poll_interval, timeout_seconds=args.timeout)
    output_dir = DEFAULT_STATE_DIR / "output"
    download_log = download_output(kernel_id, output_dir)
    payload.update(
        {
            "status": "submitted",
            "submit_output": submit_output,
            "status_output": status_output,
            "download_log": download_log,
            "output_dir": str(output_dir),
        }
    )
    print(json.dumps(payload, indent=2, sort_keys=True))
    write_state(payload)
    return 0 if "complete" in status_output.lower() else 1


if __name__ == "__main__":
    raise SystemExit(main())
